### PR TITLE
ajk/tests_multiscale

### PR DESCRIPTION
**Pull request by ajkhattak**
Added the following regression test for multiscale models:

1. permafrost multiscale models : tests for no-, static-, and dynamic-microtopography runs
2. single reach conservative tracer (a test to check ATS matches (Scott) Mathematica's results)
2. single reach denitrification test
3. watershed denitrification test
4. single reach, multisubgrid test

### CODE REVIEW

**Review by ecoon — COMMENTED** [review]
I'll double check these tests tomorrow.  I assume they all work for you on master?

**Comment by ajkhattak** [comment]
yes, I used ats master and amanzi branch (PR submitted - https://github.com/amanzi/amanzi/pull/547) for these tests.

**Comment by ecoon** [comment]
When you've dealt with Konstantin's changes, go ahead and merge all of these.  So the order is:

1. merge this pull request
2. cd to your ATS_SRC_DIR, cd testing/ats-regression-tests, git checkout master, git pull
3. cd ../../ (now in ATS_SRC_DIR), git status should show that there are new commits on ats-regression-tests.  git add, git commit, git push to master (no need for pull request here)
4. cd ../../../ (now in AMANZI_SRC_DIR), git status should show new commit in src/physics/ats, git add and push to your Amanzi pull request branch.  Then merge the Amanzi pull request.

**Comment by ecoon** [comment]
Also, can you be sure to update the README.md file with your new tests.

**Pull request merged**
