### PR TITLE
updates RT tests for tpls-0.98.8 whenever that is ready

### PR DESCRIPTION
**Pull request by smolins**
updates RT tests for tpls-0.98.8 whenever that is ready

### CODE REVIEW

**Comment by ecoon** [comment]
Great, thanks!

**Comment by ecoon** [comment]
blocked by amanzi/amanzi#792

**Comment by ecoon** [comment]
@smolins Was there anything in the PFLOTRAN input spec or reaction network spec that changed in this?  Or were these only changes due to numerical algorithms/etc?   Just curious -- I'm seeing some significant changes in another test as well, and clearly nothing in Amanzi/ATS changed enough to break things, so it must be due to changes in Alquimia or PFLOTRAN.

**Comment by smolins** [comment]
Nothing of significance changed in Alquimia, PFLOTRAN or CrunchFlow. That
both PFLOTRAN and CrunchFlow examples showed this would point to Alquimia
but again nothing really changed there. This is all a bit puzzling to me
too.

**Pull request merged**
